on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  shear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - uses: cargo-bins/cargo-binstall@e00d2c94cc0067b77737821097a62d91c0301baa # v1.21.1
      - run: cargo binstall --no-confirm cargo-shear
      - run: cargo shear
